# CREATE ROUTINE
POST http://localhost:3000/routine
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "monday": "Monday Test",
    "tuesday": "Tuesday Test",
    "wednesday": "Wednesday Test",
    "thursday": "Thursday Test",
    "friday": "Friday Test"
}

###

# GET ALL ROUTINES
GET http://localhost:3000/routine
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# GET ROUTINE BY STUDENT ID
GET http://localhost:3000/routine/student/522e3971-9bea-417c-8f49-49d06c8581d7

###

# GET ROUTINE BY ID
GET http://localhost:3000/routine/58d87028-43c2-4d34-935e-2e71d84d05c1

###

# UPDATE ROUTINE BY ID
PUT http://localhost:3000/routine/58d87028-43c2-4d34-935e-2e71d84d05c1
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "saturday": "Saturday Test",
    "sunday": "Sunday Test"
}

###

# DELETE ROUTINE BY ID
DELETE http://localhost:3000/routine/58d87028-43c2-4d34-935e-2e71d84d05c1
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
