# CREATE STUDENT
POST http://localhost:3000/student
Content-Type: application/json

{
    "name": "Student Test",
    "email": "test@student.com",
    "birthDate": "1990-01-01",
    "course": "Test Course",
    "password": "@Test123",
    "passwordConfirmation": "@Test123"
}

###

# GET ALL ACTIVE STUDENTS
GET http://localhost:3000/student

###

# GET STUDENT BY ID
GET http://localhost:3000/student/522e3971-9bea-417c-8f49-49d06c8581d7

###

# UPDATE STUDENT
PUT http://localhost:3000/student
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Student Test 2",
    "email": "test2@student.com",
    "birthDate": "2000-12-12",
    "course": "Test Course"
}

###

# UPDATE STUDENT PASSWORD
PATCH http://localhost:3000/student/password
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "currentPassword": "@Test123",
    "password": "@Test1234",
    "passwordConfirmation": "@Test1234"
}

###

# DEACTIVATE STUDENT
PATCH http://localhost:3000/student/deactivate
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# REACTIVATE STUDENT
PATCH http://localhost:3000/student/reactivate
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# DELETE STUDENT
DELETE http://localhost:3000/student
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
