# CREATE COMMENT
POST http://localhost:3000/comment
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "content": "Content Test",
    "postId": "12ea07aa-7d2e-477a-80f1-e80136c52638"
}

###

# GET COMMENT COUNT BY POST ID
GET http://localhost:3000/comment/count?postId=12ea07aa-7d2e-477a-80f1-e80136c52638

###

# GET COMMENT COUNT BY COMMENT ID
GET http://localhost:3000/comment/count?commentId=5002a7f5-fc73-41f2-af5a-5814fd4e8017

###

# GET ALL COMMENTS
GET http://localhost:3000/comment

###

# GET COMMENTS BY POST ID
GET http://localhost:3000/comment?postId=12ea07aa-7d2e-477a-80f1-e80136c52638

###

# GET COMMENTS BY COMMENT ID
GET http://localhost:3000/comment?commentId=471148db-3582-4c6e-a58f-a7f62774ab81

###

# GET COMMENTS BY STUDENT ID
GET http://localhost:3000/comment?studentId=0c5b46e0-955f-4aff-943f-6f6489cd66ea

###

# GET COMMENTS BY COLLEGE ID
GET http://localhost:3000/comment?collegeId=3b767ab8-6c07-42dd-8e7c-344c0cd29e0b

###

# GET COMMENT BY ID
GET http://localhost:3000/comment/471148db-3582-4c6e-a58f-a7f62774ab81

###

# UPDATE COMMENT BY ID
PUT http://localhost:3000/comment/471148db-3582-4c6e-a58f-a7f62774ab81
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "content": "Content Test 2"
}

###

# DELETE COMMENT BY ID
DELETE http://localhost:3000/comment/471148db-3582-4c6e-a58f-a7f62774ab81
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
