# CREATE POST
POST http://localhost:3000/post
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "content": "Content Test"
}

###

# GET ALL POSTS
GET http://localhost:3000/post

###

# GET COLLEGE POSTS
GET http://localhost:3000/post?collegeId=59c23c5e-85a8-450b-91f1-bff32a529f75

###

# GET POST BY ID
GET http://localhost:3000/post/12ea07aa-7d2e-477a-80f1-e80136c52638

###

# UPDATE POST BY ID
PUT http://localhost:3000/post/12ea07aa-7d2e-477a-80f1-e80136c52638
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "content": "Content Test 2"
}

###

# DELETE POST BY ID
DELETE http://localhost:3000/post/12ea07aa-7d2e-477a-80f1-e80136c52638
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
