# CREATE COLLEGE
POST http://localhost:3000/college
Content-Type: application/json

{
    "name": "College Test",
    "email": "test@college.com",
    "testDate": "2025-02-01",
    "phone": "(11) 1213-1415",
    "address": "Test Address",
    "password": "@Test123",
    "passwordConfirmation": "@Test123"
}

###

# GET ALL ACTIVE COLLEGES
GET http://localhost:3000/college

###

# GET COLLEGE BY ID
GET http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75

###

# UPDATE COLLEGE BY ID
PUT http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "College Test 2",
    "email": "test2@college.com",
    "testDate": "2025-01-01",
    "phone": "(12) 1314-1516",
    "address": "Test Address 2"
}

###

# UPDATE COLLEGE PASSWORD BY ID
PATCH http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75/password
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "currentPassword": "@Test123",
    "password": "@Test1234",
    "passwordConfirmation": "@Test1234"
}

###

# DEACTIVATE COLLEGE BY ID
PATCH http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75/deactivate
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# REACTIVATE COLLEGE BY ID
PATCH http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75/reactivate
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# DELETE COLLEGE BY ID
DELETE http://localhost:3000/college/59c23c5e-85a8-450b-91f1-bff32a529f75
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
