# CREATE BOOK
POST http://localhost:3000/book
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Name Test",
    "author": "Author Test"
}

###

# GET ALL BOOKS
GET http://localhost:3000/book

###

# GET COLLEGE BOOKS
GET http://localhost:3000/book?collegeId=59c23c5e-85a8-450b-91f1-bff32a529f75

###

# GET STUDENT BOOKS
GET http://localhost:3000/book?studentId=522e3971-9bea-417c-8f49-49d06c8581d7

###

# GET BOOK BY ID
GET http://localhost:3000/book/0464ddbb-b4d0-419f-9a42-1b9af3dce70d

###

# UPDATE BOOK BY ID
PUT http://localhost:3000/book/0464ddbb-b4d0-419f-9a42-1b9af3dce70d
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Name Test 2",
    "author": "Author Test 2"
}

###

# DELETE BOOK BY ID
DELETE http://localhost:3000/book/0464ddbb-b4d0-419f-9a42-1b9af3dce70d
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
