# FOLLOW OR UNFOLLOW
POST http://localhost:3000/follower
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "studentId": "73a585fb-04ef-4815-bb3d-3982c0dd53f6",
    "collegeId": "808f7526-87f6-42fa-9f63-3a3ae23bdeb0"
}

###

# CHECK IF FOLLOWING
GET http://localhost:3000/follower/check
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "studentId": "73a585fb-04ef-4815-bb3d-3982c0dd53f6",
    "collegeId": "808f7526-87f6-42fa-9f63-3a3ae23bdeb0"
}

###

# GET ALL FOLLOWERS
GET http://localhost:3000/follower

###

# GET FOLLOWERS BY COLLEGE ID
GET http://localhost:3000/follower?collegeId=808f7526-87f6-42fa-9f63-3a3ae23bdeb0

###

# GET FOLLOWERS BY STUDENT ID
GET http://localhost:3000/follower?studentId=73a585fb-04ef-4815-bb3d-3982c0dd53f6

###

# GET FOLLOWER BY ID
GET http://localhost:3000/follower/fe4d8e04-8ace-4193-b4ce-c8c3704db574
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
