# FOLLOW OR UNFOLLOW
POST http://localhost:3000/follower/59c23c5e-85a8-450b-91f1-bff32a529f75
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# CHECK IF FOLLOWING
GET http://localhost:3000/follower/59c23c5e-85a8-450b-91f1-bff32a529f75/check
Authorization: Bearer {{$dotenv AUTH_TOKEN}}

###

# GET ALL FOLLOWERS
GET http://localhost:3000/follower

###

# GET FOLLOWERS BY COLLEGE ID
GET http://localhost:3000/follower?collegeId=3b767ab8-6c07-42dd-8e7c-344c0cd29e0b

###

# GET FOLLOWERS BY STUDENT ID
GET http://localhost:3000/follower?studentId=0c5b46e0-955f-4aff-943f-6f6489cd66ea

###

# GET FOLLOWER BY ID
GET http://localhost:3000/follower/11b32fb8-4c6a-4991-b4c5-78b4c7f564b7
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
