# CREATE COURSE
POST http://localhost:3000/course
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Course Test",
    "period": "Period Test"
}

###

# GET ALL COURSES
GET http://localhost:3000/course

###

# GET COLLEGE COURSES
GET http://localhost:3000/course?collegeId=808f7526-87f6-42fa-9f63-3a3ae23bdeb0

###

# GET COURSE BY ID
GET http://localhost:3000/course/a34cb510-ed64-47c2-98cc-a9d0891a0a3d

###

# UPDATE COURSE BY ID
PUT http://localhost:3000/course/a34cb510-ed64-47c2-98cc-a9d0891a0a3d
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Course Test 2",
    "period": "Period Test 2"
}

###

# DELETE COURSE BY ID
DELETE http://localhost:3000/course/a34cb510-ed64-47c2-98cc-a9d0891a0a3d
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
