# CREATE COURSE
POST http://localhost:3000/course
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Course Test",
    "period": "Period Test"
}

###

# GET ALL COURSES
GET http://localhost:3000/course

###

# GET COLLEGE COURSES
GET http://localhost:3000/course?collegeId=59c23c5e-85a8-450b-91f1-bff32a529f75

###

# GET COURSE BY ID
GET http://localhost:3000/course/e4312151-70d2-4b17-9a12-8ea7ff09934c

###

# UPDATE COURSE BY ID
PUT http://localhost:3000/course/e4312151-70d2-4b17-9a12-8ea7ff09934c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
Content-Type: application/json

{
    "name": "Course Test 2",
    "period": "Period Test 2"
}

###

# DELETE COURSE BY ID
DELETE http://localhost:3000/course/e4312151-70d2-4b17-9a12-8ea7ff09934c
Authorization: Bearer {{$dotenv AUTH_TOKEN}}
